import Data.Char
import System.IO



main :: IO()
main = do
        frase <- readFile "frase-traduzir.txt"
        writeFile "frase-traduzida.txt" (traduzir [(minusculo letra) | letra <- frase])
        putStrLn (traduzir [(minusculo letra) | letra <- frase])
        putStrLn "\n Programa finalizado!"


        
minusculo :: Char -> Char
minusculo c | ord c <= 90 && ord c >= 65 = chr (ord c + 32)
            | otherwise = c



traduzir :: String -> String
traduzir ('p' : 't' : texto) = tradutorPtLa texto [] []
traduzir ('l' : 'a' : texto) = tradutorLaPt texto [] []
traduzir texto = "A lingua do texto nao foi reconhecida"


tradutorPtLa :: String -> String -> String -> String
tradutorPtLa (' ' : b) c d = tradutorPtLa b (c ++ " " ++ dicionarioPtLa d) []
tradutorPtLa ('\n' : b) c d = tradutorPtLa b (c ++ " " ++ dicionarioPtLa d) []
tradutorPtLa [] c d = c ++ " " ++ dicionarioPtLa d
tradutorPtLa (a : b) c d = tradutorPtLa b c (d ++ [a])



tradutorLaPt :: String -> String -> String -> String
tradutorLaPt (' ' : b) c d = tradutorLaPt b (c ++ " " ++ dicionarioLaPt d) []
tradutorLaPt ('\n' : b) c d = tradutorLaPt b (c ++ " " ++ dicionarioLaPt d) []
tradutorLaPt [] c d = c ++ " " ++ dicionarioLaPt d
tradutorLaPt (a : b) c d = tradutorLaPt b c (d ++ [a])



dicionarioPtLa :: String -> String
-- Portugues -> Latim
dicionarioPtLa "eu" = "ego"
dicionarioPtLa "tu" = "vos"
dicionarioPtLa "ele" = "quod"
dicionarioPtLa "ela" = "quae"
dicionarioPtLa "nos" = "nobis"
dicionarioPtLa "vamos" = "abeamus"
dicionarioPtLa "sua" = "vestra"
dicionarioPtLa "casa" = "domum"
dicionarioPtLa "primeiro" = "primus"
dicionarioPtLa "justica" = "iustitia"
dicionarioPtLa "lapis" = "plumbum"
dicionarioPtLa "coisas" = "supellectilem"
dicionarioPtLa "senhor" = "dominus"
dicionarioPtLa "mao" = "manibus"
dicionarioPtLa "boa" = "bonum"
dicionarioPtLa "nao" = "non"
dicionarioPtLa "sim" = "etiam"
dicionarioPtLa "ajudo" = "auxilium"
dicionarioPtLa "estudos" = "studium"
dicionarioPtLa "efeito" = "modum"
dicionarioPtLa "procura" = "demanda"
dicionarioPtLa "analise" = "analysis"
dicionarioPtLa "enfermo" = "infirmu"
dicionarioPtLa "estelionato" = "stellionatu"
dicionarioPtLa "estilo" = "stilu"
dicionarioPtLa "imbecil" = "imbecille"
dicionarioPtLa "teoria" = "doctrina"
dicionarioPtLa "valor" = "valorem"
dicionarioPtLa "dados" = "notitia"
dicionarioPtLa "pessoa" = "hominem"
dicionarioPtLa "arvore" = "lignum"
dicionarioPtLa "laranja" = "aurantiaco"
dicionarioPtLa "renda" = "reditus"
dicionarioPtLa "mercado" = "forum"
dicionarioPtLa "politica" = "consilium"
dicionarioPtLa "ataque" = "impetus"
dicionarioPtLa "agua" = "aqua"
dicionarioPtLa "corrupcao" = "corruptio"
dicionarioPtLa "maca" = "malum"
dicionarioPtLa "corda" = "funem"
dicionarioPtLa "meia" = "metus"
dicionarioPtLa "medico" = "medicus"
dicionarioPtLa "crianca" = "puer"
dicionarioPtLa "vinho" = "vinum"
dicionarioPtLa "pao" = "panem"
dicionarioPtLa "mais" = "magis"
dicionarioPtLa "forte" = "fortiori"
dicionarioPtLa "lado" = "latere"
dicionarioPtLa "o" = "domino"
dicionarioPtLa "segundo" = "posteriori"
dicionarioPtLa "razao" = "ratione"
dicionarioPtLa "particular" = "remotis"
dicionarioPtLa "sagrado" = "sacris"
dicionarioPtLa "eterno" = "aeterno"
dicionarioPtLa "convidativo" = "petamus"
dicionarioPtLa "honroso" = "honesta"
dicionarioPtLa "amigos" = "amicis"
dicionarioPtLa "letras" = "epistolis"
dicionarioPtLa "de" = "ab"
dicionarioPtLa "isto" = "hoc"
dicionarioPtLa "esta" = "hac"
dicionarioPtLa "e" = "et"
dicionarioPtLa "fundo" = "imo"
dicionarioPtLa "coracao" = "corde"
dicionarioPtLa "peito" = "pectore"
dicionarioPtLa "berco" = "incunabulis"
dicionarioPtLa "comeco" = "initio"
dicionarioPtLa "enfurecido" = "irato"
dicionarioPtLa "boca" = "ore"
dicionarioPtLa "ouvido" = "aurem"
dicionarioPtLa "origem" = "origine"
dicionarioPtLa "um" = "uno"
dicionarioPtLa "tudo" = "omnes"
dicionarioPtLa "cidade" = "urbe"
dicionarioPtLa "fundacao" = "condita"
dicionarioPtLa "causa" = "causae"
dicionarioPtLa "desvio" = "aberratio"
dicionarioPtLa "ofensa" = "delicti"
dicionarioPtLa "chega" = "venit"
dicionarioPtLa "pra" = "ut"
dicionarioPtLa "ca" = "hic"
dicionarioPtLa "meu" = "mea"
dicionarioPtLa "bem" = "tum"
dicionarioPtLa "vou" = "autem"
dicionarioPtLa "ensinar" = "doceat"
dicionarioPtLa "nossa" = "noster"
dicionarioPtLa "danca" = "chorus"
dicionarioPtLa "estado" = "statum"
dicionarioPtLa "do" = "auntem"
dicionarioPtLa "chegou" = "advenimus"
dicionarioPtLa "ficar" = "menere"
dicionarioPtLa "nesse" = "inoc"
dicionarioPtLa "swing" = "adductius"
dicionarioPtLa "voce" = "vobis"
dicionarioPtLa "tambem" = "item"
dicionarioPtLa "entrar" = "intrabit"
dicionarioPtLa "mexa" = "suscitare"
dicionarioPtLa "pezinho" = "porphyrio"
dicionarioPtLa "vai" = "erit"
dicionarioPtLa "soltando" = "stillabunt"
dicionarioPtLa "corpo" = "corpus"
dicionarioPtLa "depois" = "post"
dicionarioPtLa "abraca" = "cubantem"
dicionarioPtLa "com" = "apud"
dicionarioPtLa "carinho" = "affectio"
dicionarioPtLa "gente" = "populus"
dicionarioPtLa "pode" = "potes"
dicionarioPtLa "fazer" = "facite"
dicionarioPtLa "outra" = "alium"
dicionarioPtLa "vez" = "tempus"

-- palavra nao reconhecida
dicionarioPtLa x = x



dicionarioLaPt :: String -> String
-- Latim -> Portugues
dicionarioLaPt "ego" = "eu"
dicionarioLaPt "vos" = "tu"
dicionarioLaPt "quod" = "ele"
dicionarioLaPt "quae" = "ela"
dicionarioLaPt "nobis" = "nos"
dicionarioLaPt "abeamus" = "vamos"
dicionarioLaPt "vestra" = "sua"
dicionarioLaPt "domum" = "casa"
dicionarioLaPt "primus" = "primeiro"
dicionarioLaPt "iustitia" = "justica"
dicionarioLaPt "plumbum" = "lapis"
dicionarioLaPt "supellectilem" = "coisas"
dicionarioLaPt "dominus" = "senhor"
dicionarioLaPt "manibus" = "mao"
dicionarioLaPt "bonum" = "boa"
dicionarioLaPt "non" = "nao"
dicionarioLaPt "etiam" = "sim"
dicionarioLaPt "auxilium" = "ajudo"
dicionarioLaPt "studium" = "estudos"
dicionarioLaPt "modum" = "efeito"
dicionarioLaPt "demanda" = "procura"
dicionarioLaPt "analysis" = "analise"
dicionarioLaPt "infirmu" = "enfermo"
dicionarioLaPt "stellionatu" = "estelionato"
dicionarioLaPt "stilu" = "estilo"
dicionarioLaPt "imbecille" = "imbecil"
dicionarioLaPt "doctrina" = "teoria"
dicionarioLaPt "valorem" = "valor"
dicionarioLaPt "notitia" = "dados"
dicionarioLaPt "hominem" = "pessoa"
dicionarioLaPt "lignum" = "arvore"
dicionarioLaPt "aurantiaco" = "laranja"
dicionarioLaPt "reditus" = "renda"
dicionarioLaPt "forum" = "mercado"
dicionarioLaPt "consilium" = "politica"
dicionarioLaPt "impetus" = "ataque"
dicionarioLaPt "aqua" = "agua"
dicionarioLaPt "corruptio" = "corrupcao"
dicionarioLaPt "malum" = "maca"
dicionarioLaPt "funem" = "corda"
dicionarioLaPt "metus" = "meia"
dicionarioLaPt "medicus" = "medico"
dicionarioLaPt "puer" = "crianca"
dicionarioLaPt "vinum" = "vinho"
dicionarioLaPt "panem" = "pao"
dicionarioLaPt "magis" = "mais"
dicionarioLaPt "fortiori" = "forte"
dicionarioLaPt "latere" = "lado"
dicionarioLaPt "domino" = "o"
dicionarioLaPt "posteriori" = "segundo"
dicionarioLaPt "ratione" = "razao"
dicionarioLaPt "remotis" = "particular"
dicionarioLaPt "sacris" = "sagrado"
dicionarioLaPt "aeterno" = "eterno"
dicionarioLaPt "petamus" = "convidativo"
dicionarioLaPt "honesta" = "honroso"
dicionarioLaPt "amicis" = "amigos"
dicionarioLaPt "epistolis" = "letras"
dicionarioLaPt "ab" = "de"
dicionarioLaPt "hoc" = "isto"
dicionarioLaPt "hac" = "esta"
dicionarioLaPt "et" = "e"
dicionarioLaPt "imo" = "fundo"
dicionarioLaPt "corde" = "coracao"
dicionarioLaPt "pectore" = "peito"
dicionarioLaPt "incunabulis" = "berco"
dicionarioLaPt "initio" = "comeco"
dicionarioLaPt "irato" = "enfurecido"
dicionarioLaPt "ore" = "boca"
dicionarioLaPt "aurem" = "ouvido"
dicionarioLaPt "origine" = "origem"
dicionarioLaPt "uno" = "um"
dicionarioLaPt "omnes" = "tudo"
dicionarioLaPt "urbe" = "cidade"
dicionarioLaPt "condita" = "fundacao"
dicionarioLaPt "causae" = "causa"
dicionarioLaPt "aberratio" = "desvio"
dicionarioLaPt "delicti" = "ofensa"
dicionarioLaPt "venit" = "chega"
dicionarioLaPt "ut" = "pra"
dicionarioLaPt "hic" = "ca"
dicionarioLaPt "mea" = "meu"
dicionarioLaPt "tum" = "bem"
dicionarioLaPt "autem" = "vou"
dicionarioLaPt "doceat" = "ensinar"
dicionarioLaPt "noster" = "nossa"
dicionarioLaPt "chorus" = "danca"
dicionarioLaPt "statum" = "estado"
dicionarioLaPt "auntem" = "do"
dicionarioLaPt "advenimus" = "chegou"
dicionarioLaPt "menere" = "ficar"
dicionarioLaPt "inoc" = "nesse"
dicionarioLaPt "adductius" = "swing"
dicionarioLaPt "vobis" = "voce"
dicionarioLaPt "item" = "tambem"
dicionarioLaPt "intrabit" = "entrar"
dicionarioLaPt "suscitare" = "mexa"
dicionarioLaPt "porphyrio" = "pezinho"
dicionarioLaPt "erit" = "vai"
dicionarioLaPt "stillabunt" = "soltando"
dicionarioLaPt "corpus" = "corpo"
dicionarioLaPt "post" = "depois"
dicionarioLaPt "cubantem" = "abraca"
dicionarioLaPt "apud" = "com"
dicionarioLaPt "affectio" = "carinho"
dicionarioLaPt "populus" = "gente"
dicionarioLaPt "potes" = "pode"
dicionarioLaPt "facite" = "fazer"
dicionarioLaPt "alium" = "outra"
dicionarioLaPt "tempus" = "vez"

-- palavra nao reconhecida
dicionarioLaPt x = x
